defaults:
  - _self_
  - models: resnet50
  - dataset: OL3I_coarse

# Command Center
pretrain: True
run_eval: False
evaluate: False
test: False
test_and_eval: False
combine_train_and_val: True
generate_embeddings: False
run_name_set: 'offline_exp1'
gpus: [2]

seeds: 
  - 2022
  - 2023
  - 2024
  - 2025
  - 2026
lr_finder_lrs: 
  - 3.e-2
  - 1.e-2
  - 3.e-3
  - 1.e-3
  - 3.e-4
  - 1.e-4
multitarget:

wandb_entity: jasminey204-Sun Yat-sen University
data_base: '/media/HDD1/yucj/OL3I/data_file_423/'
num_workers: 48

wandb_project: Multi-Grained-Tabular-Images
sql_address: 

# Multimodal
weight_decay: 1.e-4
scheduler: anneal
anneal_max_epochs: 200
warmup_epochs: 10
temperature: 0.1
projection_dim: 128
input_channel: 1
use_projection_head: True

batch_size: 32

loss: clip
view: augmented
lambda_0: 0.5
momentum: 0.99
multiple_lr: False

train_similarity_matrix:
val_similarity_matrix: 
threshold: 0.9
similarity_divisor: 2

tabular_pretrain_checkpoint: 
pretrained_tabular_strategy: 
imaging_pretrain_checkpoint: 
pretrained_imaging_strategy: 

# Imaging
augmentation_rate: 0.95
crop_scale_lower: 0.08

# tabular
corruption_rate: 0.3
one_hot: False
eval_one_hot: False

tabular_encoder: FT-Mamba
encoder_num_layers: 2
projector_num_layers: 1
init_strat: kaiming
n_cont_features: 423
cat_cardinalities: []
n_categories: []

# Evaluator
keep_projector: False
eval_train_augment_rate: 0.8
eval_classifier: linear
finetune_strategy: frozen
eval_loss: focal
alpha: [0.1, 2]

vec2vec: False
checkpoint_vec2vec: 

checkpoint: 
datatype: multimodal
eval_datatype: imaging_and_tabular

lr_eval: 1.e-2
weight_decay_eval: 0
val_check_interval: 1
check_val_every_n_epoch: 1

# Classifier
classifier_num_layers: 2
lr_classifier: 3.e-4
weight_decay_classifier: 1.e-4
online_mlp: True

# General
seed: 2022
max_epochs: 500
log_images: False
use_wandb: True
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
enable_progress_bar: True
offline: True
weighted_sampler:
classifier_freq: 5
unit_test: False

transform:
version:
input_size:
transform_train:
transform_val:
transform_test:
dataset_length:
resume_training: 
wandb_id: 

labels_train_short:
labels_val_short:
data_train_tabular_short:
data_val_tabular_short:
data_train_imaging_short:
data_val_imaging_short:
field_lengths_tabular_short:
data_train_eval_tabular_short:
labels_train_eval_tabular_short:
data_val_eval_tabular_short:
labels_val_eval_tabular_short:
data_test_eval_tabular_short:
labels_test_eval_tabular_short:
data_train_eval_imaging_short:
labels_train_eval_imaging_short:
data_val_eval_imaging_short:
labels_val_eval_imaging_short:
data_test_eval_imaging_short:
labels_test_eval_imaging_short:
train_similarity_matrix_short: